# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-17 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, choices=[('MA', 'Maurice'), ('FR', 'France'), ('BF', 'Bachelorette'), ('BH', 'Bacelor'), ('SU', 'Surprise-Maries')], max_length=50),
        ),
    ]
