# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-17 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20160517_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, choices=[('Maurice', 'Maurice'), ('France', 'France'), ('Bachelorette', 'Bachelorette'), ('Bachelor', 'Bachelor'), ('Surpise Maries', 'Surprise-Maries')], max_length=50),
        ),
    ]
